### ISSUE TITLE
Failing to connect to remote server (nrobot-server) with Fault 1: Type RPC2 not loaded

### ISSUE THREAD

**Issue by mig-l-f** [claytonneal/nrobot-server#5]
Hi,

I'm not sure this is the correct route for support but was the only i found. I've cloned and compiled master locally, have a nrobot-server running locally at http://127.0.0.1:8721, using the webbrowser can list the available keywords in the remote server. Though when connecting via a resource with pybot i get the following error:
_Getting keyword names from library 'Remote' failed: Calling dynamic method 'get_keyword_names' failed: Connecting remote server  at http://127.0.0.1:8271 failed: <Fault 1: 'Type RPC2 is not loaded'>_

The nrobot-server is running prior to executing pybot. Below is my resource, the REMOTE_LIBRARY_URL_WITH_PORT is passed on at execution time. And the keyword Write Hello World To File is listed in the browser at http://127.0.0.1:8271

Any help would be greatly appreciated? 
Thanks
Miguel

*** Settings ***
Documentation    Hello World resource for linking with remote library
Library    Remote    ${REMOTE_LIBRARY_URL_WITH_PORT}    WITH NAME    Remote
*** Variables ***
*** Keywords ***
Write Hello World To File
    [Arguments]     ${directory_path}
    Remote.Write Hello World To File    ${directory_path}

**Comment by claytonneal** [comment]
Hiya, 
The url you are passing is incorrect - NRobot has host multiple classes, and exposes each keyword class on its own url. So the url you need to give is like:
http://127.0.0.1:8271/<c# namespace>/<c #classname>
And replace "." in namespace with "/"
Thanks

**Comment by mig-l-f** [comment]
Thanks that worked.
