### ISSUE TITLE
RPC2 is not loaded

### ISSUE THREAD

**Issue by gsumano** [claytonneal/nrobot-server#6]
Robot Framework cannot get keyword names from the server.   Looking at the log file, it shows an exception with XmlRpcService  : 
[17] DEBUG NRobot.Server.Imp.Services.XmlRpcService - XmlRpc Method call - get_keyword_names
 [17] ERROR NRobot.Server.Imp.Services.XmlRpcService - Exception in method - get_keyword_names : Type RPC2 is not loaded

**Comment by gsumano** [comment]
My fault I found out that I need to specify the class name

**Comment by gsumano** [comment]
My fault I found out that I need to specify the class name

**Comment by claytonneal** [comment]
No problem, yeah nrobot can host multiple keyword assemblies (dlls). It separates them via the URL, which is the full class name (with namespace), with dots replaced by slashes.
